### ISSUE TITLE
Hey can you give one last update for epub_viewer . 

### ISSUE THREAD

**Issue by pruthvi1698** [JideGuru/rich_editor#29]

**Comment by pruthvi1698** [comment]
Android 12 issue is coming.
on targetSdkVersion 31


The error for building:
 Error:
        android:exported needs to be explicitly specified for element <activity#app.ruthumana.MainActivity>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.

**Comment by JideGuru** [comment]
Hi there,
Sorry, but I won't be making any updates to the `epub_viewer` plugin. I recommend that you use https://github.com/Mantano/iridium_reader_widget instead

**Comment by pruthvi1698** [comment]
1 last update please

**Comment by pruthvi1698** [comment]
Only this issue. 
Error:
android:exported needs to be explicitly specified for element <activity#app.ruthumana.MainActivity>. Apps targeting Android 12 and higher are required to specify an explicit value for android:exported when the corresponding component has an intent filter defined

**Comment by pruthvi1698** [comment]
I have pushed the ios release. struck with android. please help
