### ISSUE TITLE
Is the value from the editor can only be HTML?

### ISSUE THREAD

**Issue by SeasonLeee** [JideGuru/rich_editor#7]
As stated in the title, is there a way to get the value in object like structure? 

Thanks!

**Comment by JideGuru** [comment]
The editor work only with html so you can only get it in html. I do not have any intentions of supporting anything other than html in the future. Perhaps you can write a piece of code that converts the html to whatever structure you need. Thanks

**Comment by SeasonLeee** [comment]
Oh... Alright... And one last question, could you share your experience on how to develop an editor like this? 

I know this question could take time but... In our project we really need a rich text editor...

**Comment by JideGuru** [comment]
If you need an editor that's not HTML check out https://pub.dev/packages/zefyr and https://pub.dev/packages/markdown_editable_textinput
